export const TRY_OUT_RESULT_STATES = {
    START: 'START',
    ERROR: 'ERROR',
    VALID_PROGRESS: 'VALID_PROGRESS'
}

export const TRY_OUT_ERROR_TYPES = {
    MULTIPLE_CELLS_NAKED_SINGLE: 'MULTIPLE_CELLS_NAKED_SINGLE',
    EMPTY_CELL_IN_SOLUTION: 'EMPTY_CELL_IN_SOLUTION'
}