const ACTION_TYPES = {
    ON_ERASE_CLICK: 'ON_ERASE_CLICK',
    ON_NUMBER_CLICK: 'ON_NUMBER_CLICK',
}
export const INPUT_PANEL_CONTAINER_TEST_ID = 'INPUT_PANEL_CONTAINER_TEST_ID'

export const INPUT_PANEL_ITEM_TEST_ID = 'INPUT_PANEL_ITEM_TEST_ID'

export { ACTION_TYPES }
