export const HINTS_VOCAB_IDS = {
    CANDIDATE: 'CANDIDATE',
    NAKED_SINGLE: 'NAKED_SINGLE',
    HIDDEN_SINGLE: 'HIDDEN_SINGLE',
    HIDDEN_DOUBLE: 'HIDDEN_DOUBLE',
    HOUSE: 'HOUSE',
    CELL: 'CELL',
    ROW: 'ROW',
    COLUMN: 'COLUMN',
    BLOCK: 'BLOCK',
}
