import { HOUSE_TYPE } from '@domain/board/board.constants'

export enum HINTS_VOCAB_IDS {
    CANDIDATE = 'CANDIDATE',
    HOUSE = 'HOUSE',
    CELL = 'CELL',
    ROW = 'ROW',
    COLUMN = 'COLUMN',
    BLOCK = 'BLOCK',
    NAKED_SINGLE = 'NAKED_SINGLE',
    NAKED_DOUBLE = 'NAKED_DOUBLE',
    NAKED_TRIPPLE = 'NAKED_TRIPPLE',
    HIDDEN_SINGLE = 'HIDDEN_SINGLE',
    HIDDEN_DOUBLE = 'HIDDEN_DOUBLE',
    HIDDEN_TRIPPLE = 'HIDDEN_TRIPPLE',
    OMISSION = 'OMISSION',
    CHAIN_LINKS = 'CHAIN_LINKS',
    CHAIN = 'CHAIN',
    REMOTE_PAIRS = 'REMOTE_PAIRS',
    X_CHAIN = 'X_CHAIN',
    XY_CHAIN = 'XY_CHAIN',
    PERFECT_X_WING = 'PERFECT_X_WING',
    FINNED_X_WING = 'FINNED_X_WING',
    SASHIMI_FINNED_X_WING = 'SASHIMI_FINNED_X_WING',
    X_WING_CORNER_CELLS = 'X_WING_CORNER_CELLS',
    X_WING_FINN_CELLS = 'X_WING_FINN_CELLS'
}

export const HOUSE_TYPE_VS_VOCAB_ID = {
    [HOUSE_TYPE.ROW]: HINTS_VOCAB_IDS.ROW,
    [HOUSE_TYPE.COL]: HINTS_VOCAB_IDS.COLUMN,
    [HOUSE_TYPE.BLOCK]: HINTS_VOCAB_IDS.BLOCK,
}
