export enum HINTS_VOCAB_IDS {
    CANDIDATE = 'CANDIDATE',
    HOUSE = 'HOUSE',
    CELL = 'CELL',
    ROW = 'ROW',
    COLUMN = 'COLUMN',
    BLOCK = 'BLOCK',
    NAKED_SINGLE = 'NAKED_SINGLE',
    NAKED_DOUBLE = 'NAKED_DOUBLE',
    NAKED_TRIPPLE = 'NAKED_TRIPPLE',
    HIDDEN_SINGLE = 'HIDDEN_SINGLE',
    HIDDEN_DOUBLE = 'HIDDEN_DOUBLE',
    HIDDEN_TRIPPLE = 'HIDDEN_TRIPPLE',
    OMISSION = 'OMISSION',
    CHAIN_LINKS = 'CHAIN_LINKS'
}
