export const FOOTER_BUTTONS_TEXT = {
    NEXT: 'Next',
    PREV: 'Prev',
    APPLY_HINT: 'Apply Hint',
}

export const SMART_HINT_CHANGES_APPLY_DELAY = 100

export const SMART_HINT_HC_TEST_ID = 'SMART_HINT_HC_TEST_ID'

export const CLOSE_ICON_TEST_ID = 'CLOSE_ICON_TEST_ID'

export const SMART_HINT_HC_BOTTOM_DRAGGER_CHILD_TEST_ID = 'SMART_HINT_HC_BOTTOM_DRAGGER_CHILD_TEST_ID'

export const SMART_HINT_HC_STEP_COUNT_TEXT_TEST_ID = 'SMART_HINT_HC_STEP_COUNT_TEXT_TEST_ID'
