import { HINTS_IDS } from '../utils/smartHints/constants'
import { HINTS_VOCAB_IDS } from '../utils/smartHints/rawHintTransformers'

export const FOOTER_BUTTONS_TEXT = {
    NEXT: 'Next',
    PREV: 'Prev',
    APPLY_HINT: 'Apply Hint',
}

export const SMART_HINT_CHANGES_APPLY_DELAY = 100

export const SMART_HINT_HC_TEST_ID = 'SMART_HINT_HC_TEST_ID'

export const CLOSE_ICON_TEST_ID = 'CLOSE_ICON_TEST_ID'

export const SMART_HINT_HC_BOTTOM_DRAGGER_CHILD_TEST_ID = 'SMART_HINT_HC_BOTTOM_DRAGGER_CHILD_TEST_ID'

export const SMART_HINT_HC_STEP_COUNT_TEXT_TEST_ID = 'SMART_HINT_HC_STEP_COUNT_TEXT_TEST_ID'

export const HINT_VS_VOCAB_ID = {
    [HINTS_IDS.NAKED_SINGLE]: HINTS_VOCAB_IDS.NAKED_SINGLE,
    [HINTS_IDS.NAKED_DOUBLE]: HINTS_VOCAB_IDS.NAKED_DOUBLE,
    [HINTS_IDS.NAKED_TRIPPLE]: HINTS_VOCAB_IDS.NAKED_TRIPPLE,
    [HINTS_IDS.HIDDEN_SINGLE]: HINTS_VOCAB_IDS.HIDDEN_SINGLE,
    [HINTS_IDS.HIDDEN_DOUBLE]: HINTS_VOCAB_IDS.HIDDEN_DOUBLE,
    [HINTS_IDS.HIDDEN_TRIPPLE]: HINTS_VOCAB_IDS.HIDDEN_TRIPPLE,
    [HINTS_IDS.REMOTE_PAIRS]: HINTS_VOCAB_IDS.REMOTE_PAIRS,
    [HINTS_IDS.X_CHAIN]: HINTS_VOCAB_IDS.X_CHAIN,
    [HINTS_IDS.XY_CHAIN]: HINTS_VOCAB_IDS.XY_CHAIN,
    [HINTS_IDS.PERFECT_X_WING]: HINTS_VOCAB_IDS.PERFECT_X_WING,
    [HINTS_IDS.FINNED_X_WING]: HINTS_VOCAB_IDS.FINNED_X_WING,
    [HINTS_IDS.SASHIMI_FINNED_X_WING]: HINTS_VOCAB_IDS.SASHIMI_FINNED_X_WING,
    [HINTS_IDS.EMPTY_RECTANGLE]: HINTS_VOCAB_IDS.EMPTY_RECTANGLE
}
