export enum LEG_TYPES {
    PERFECT = 'PERFECT',
    FINNED = 'FINNED',
    INVALID = 'INVALID',
    SASHIMI_FINNED = 'SASHIMI_FINNED',
}

export enum XWING_TYPES {
    PERFECT = 'PERFECT',
    FINNED = 'FINNED',
    INVALID = 'INVALID',
    SASHIMI_FINNED = 'SASHIMI_FINNED',
}
