const Color = require('color')

// we will make out palettes using this algorithm
// take hue and chroma from themebuilder (https://m3.material.io/theme-builder#/custom)
// and just change the lightness as per the variant is required

const lightnessList = [10, 20, 30, 40, 50, 60, 70, 80, 87, 90, 92, 94, 95, 96, 98, 99]

const colorHSL = Color('#B3261E').hsl()

const result = {}

lightnessList.forEach(lightnessVale => {
    const color = Color({
        h: colorHSL.color[0],
        s: colorHSL.color[1],
        l: lightnessVale,
    })
    result[lightnessVale] = {
        value: color.hex(),
        isCore: true,
    }
})
console.log(result)

module.exports = {
    colors: {
        white: { value: '#FFFFFF', isCore: true },
        black: { value: '#000000', isCore: true },
        primary: {
            0: { value: '{colors.black}', isCore: true },
            10: { value: '#140B28', isCore: true },
            20: { value: '#281551', isCore: true },
            30: { value: '#3C2079', isCore: true },
            40: { value: '#4F2AA2', isCore: true },
            50: { value: '#6335CA', isCore: true },
            60: { value: '#825DD5', isCore: true },
            70: { value: '#A286DF', isCore: true },
            80: { value: '#C1AEEA', isCore: true },
            87: { value: '#D6CBF1', isCore: true },
            90: { value: '#E0D7F4', isCore: true },
            92: { value: '#E6DFF6', isCore: true },
            94: { value: '#ECE7F9', isCore: true },
            95: { value: '#EFEBFA', isCore: true },
            96: { value: '#F3EFFB', isCore: true },
            98: { value: '#F9F7FD', isCore: true },
            99: { value: '#FCFBFE', isCore: true },
            100: { value: '{colors.white}', isCore: true },
        },
        secondary: {
            0: { value: '{colors.black}', isCore: true },
            10: { value: '#18151E', isCore: true },
            20: { value: '#2F2A3C', isCore: true },
            30: { value: '#473F5A', isCore: true },
            40: { value: '#5F5379', isCore: true },
            50: { value: '#766897', isCore: true },
            60: { value: '#9286AC', isCore: true },
            70: { value: '#ADA5C0', isCore: true },
            80: { value: '#C8C3D5', isCore: true },
            87: { value: '#DBD8E4', isCore: true },
            90: { value: '#E4E1EA', isCore: true },
            92: { value: '#E9E7EE', isCore: true },
            94: { value: '#EFEDF2', isCore: true },
            95: { value: '#F1F0F5', isCore: true },
            96: { value: '#F4F3F7', isCore: true },
            98: { value: '#FAF9FB', isCore: true },
            99: { value: '#FCFCFD', isCore: true },
            100: { value: '{colors.white}', isCore: true },
        },
        tertiary: {
            0: { value: '{colors.black}', isCore: true },
            10: { value: '#201317', isCore: true },
            20: { value: '#40262E', isCore: true },
            30: { value: '#603946', isCore: true },
            40: { value: '#804C5D', isCore: true },
            50: { value: '#A05F74', isCore: true },
            60: { value: '#B37F90', isCore: true },
            70: { value: '#C69FAC', isCore: true },
            80: { value: '#D9BFC7', isCore: true },
            87: { value: '#E6D5DB', isCore: true },
            90: { value: '#ECDFE3', isCore: true },
            92: { value: '#F0E5E9', isCore: true },
            94: { value: '#F4ECEE', isCore: true },
            95: { value: '#F5EFF1', isCore: true },
            96: { value: '#F7F2F4', isCore: true },
            98: { value: '#FBF9F9', isCore: true },
            99: { value: '#FDFCFC', isCore: true },
            100: { value: '{colors.white}', isCore: true },
        },
        neutral: {
            0: { value: '{colors.black}', isCore: true },
            10: { value: '#1C181C', isCore: true },
            20: { value: '#372F37', isCore: true },
            30: { value: '#524752', isCore: true },
            40: { value: '#6E5E6E', isCore: true },
            50: { value: '#8A768A', isCore: true },
            60: { value: '#A191A1', isCore: true },
            70: { value: '#B8ADB8', isCore: true },
            80: { value: '#D0C8D0', isCore: true },
            87: { value: '#E0DBE0', isCore: true },
            90: { value: '#E8E3E8', isCore: true },
            92: { value: '#ECE9EC', isCore: true },
            94: { value: '#F1EFF1', isCore: true },
            95: { value: '#F3F1F3', isCore: true },
            96: { value: '#F6F4F6', isCore: true },
            98: { value: '#FAFAFA', isCore: true },
            99: { value: '#FDFCFD', isCore: true },
            100: { value: '{colors.white}', isCore: true },
        },
        'neutral-variant': {
            0: { value: '{colors.black}', isCore: true },
            10: { value: '#1A181C', isCore: true },
            20: { value: '#332F37', isCore: true },
            30: { value: '#4D4752', isCore: true },
            40: { value: '#665E6E', isCore: true },
            50: { value: '#7F768A', isCore: true },
            60: { value: '#9991A1', isCore: true },
            70: { value: '#B3ADB8', isCore: true },
            80: { value: '#CCC8D0', isCore: true },
            87: { value: '#DEDBE0', isCore: true },
            90: { value: '#E6E3E8', isCore: true },
            92: { value: '#EBE9EC', isCore: true },
            94: { value: '#F0EFF1', isCore: true },
            95: { value: '#F2F1F3', isCore: true },
            96: { value: '#F5F4F6', isCore: true },
            98: { value: '#FAFAFA', isCore: true },
            99: { value: '#FCFCFD', isCore: true },
            100: { value: '{colors.white}', isCore: true },
        },
        error: {
            0: { value: '{colors.black}', isCore: true },
            10: { value: '#2C0907', isCore: true },
            20: { value: '#57130F', isCore: true },
            30: { value: '#831C16', isCore: true },
            40: { value: '#AF251D', isCore: true },
            50: { value: '#DA2E25', isCore: true },
            60: { value: '#E25850', isCore: true },
            70: { value: '#E9827C', isCore: true },
            80: { value: '#F0ACA8', isCore: true },
            87: { value: '#F5C9C6', isCore: true },
            90: { value: '#F8D5D3', isCore: true },
            92: { value: '#F9DEDC', isCore: true },
            94: { value: '#FBE6E5', isCore: true },
            95: { value: '#FBEAE9', isCore: true },
            96: { value: '#FCEEEE', isCore: true },
            98: { value: '#FEF7F6', isCore: true },
            99: { value: '#FEFBFB', isCore: true },
            100: { value: '{colors.white}', isCore: true },
        },
    },
}
