module.exports = {
    colors: {
        white: { value: '#FFFFFF', isCore: true },
        black: { value: '#000000', isCore: true },
        primary: {
            0: { value: '{colors.black}', isCore: true },
            10: { value: '#001550', isCore: true },
            20: { value: '#002780', isCore: true },
            30: { value: '#003ab3', isCore: true },
            40: { value: '#2653d3', isCore: true },
            50: { value: '#466ded', isCore: true },
            60: { value: '#6889ff', isCore: true },
            70: { value: '#90a7ff', isCore: true },
            80: { value: '#b6c4ff', isCore: true },
            87: { value: '#d1d8ff', isCore: true },
            90: { value: '#dce1ff', isCore: true },
            92: { value: '#e4e7ff', isCore: true },
            94: { value: '#ebedff', isCore: true },
            95: { value: '#eff0ff', isCore: true },
            96: { value: '#f3f2ff', isCore: true },
            98: { value: '#faf8ff', isCore: true },
            99: { value: '#fefbff', isCore: true },
            100: { value: '{colors.white}', isCore: true },
        },
        secondary: {
            0: { value: '{colors.black}', isCore: true },
            10: { value: '#161b2c', isCore: true },
            20: { value: '#2b3042', isCore: true },
            30: { value: '#424659', isCore: true },
            40: { value: '#595d72', isCore: true },
            50: { value: '#72768b', isCore: true },
            60: { value: '#8c90a6', isCore: true },
            70: { value: '#a6aac1', isCore: true },
            80: { value: '#c2c5dd', isCore: true },
            87: { value: '#d5d9f1', isCore: true },
            90: { value: '#dee1f9', isCore: true },
            92: { value: '#e4e7ff', isCore: true },
            94: { value: '#ebedff', isCore: true },
            95: { value: '#eff0ff', isCore: true },
            96: { value: '#f3f2ff', isCore: true },
            98: { value: '#faf8ff', isCore: true },
            99: { value: '#fefbff', isCore: true },
            100: { value: '{colors.white}', isCore: true },
        },
        tertiary: {
            0: { value: '{colors.black}', isCore: true },
            10: { value: '#2c122a', isCore: true },
            20: { value: '#432740', isCore: true },
            30: { value: '#5b3d57', isCore: true },
            40: { value: '#755470', isCore: true },
            50: { value: '#8f6c89', isCore: true },
            60: { value: '#aa85a3', isCore: true },
            70: { value: '#c69fbf', isCore: true },
            80: { value: '#e3bada', isCore: true },
            87: { value: '#f8ceee', isCore: true },
            90: { value: '#ffd7f6', isCore: true },
            92: { value: '#ffdff6', isCore: true },
            94: { value: '#ffe7f7', isCore: true },
            95: { value: '#ffebf8', isCore: true },
            96: { value: '#ffeff8', isCore: true },
            98: { value: '#fff7f9', isCore: true },
            99: { value: '#fffbff', isCore: true },
            100: { value: '{colors.white}', isCore: true },
        },
        neutral: {
            0: { value: '{colors.black}', isCore: true },
            10: { value: '#1b1b1f', isCore: true },
            20: { value: '#303033', isCore: true },
            30: { value: '#46464a', isCore: true },
            40: { value: '#5e5e62', isCore: true },
            50: { value: '#77767a', isCore: true },
            60: { value: '#919094', isCore: true },
            70: { value: '#acaaaf', isCore: true },
            80: { value: '#c7c6ca', isCore: true },
            87: { value: '#dbd9dd', isCore: true },
            90: { value: '#e4e2e6', isCore: true },
            92: { value: '#e9e7ec', isCore: true },
            94: { value: '#efedf1', isCore: true },
            95: { value: '#f2f0f4', isCore: true },
            96: { value: '#f5f3f7', isCore: true },
            98: { value: '#fbf8fd', isCore: true },
            99: { value: '#fefbff', isCore: true },
            100: { value: '{colors.white}', isCore: true },
        },
        'neutral-variant': {
            0: { value: '{colors.black}', isCore: true },
            10: { value: '#1a1b23', isCore: true },
            20: { value: '#2f3038', isCore: true },
            30: { value: '#45464f', isCore: true },
            40: { value: '#5d5e67', isCore: true },
            50: { value: '#767680', isCore: true },
            60: { value: '#90909a', isCore: true },
            70: { value: '#abaab5', isCore: true },
            80: { value: '#c6c5d0', isCore: true },
            87: { value: '#dad9e4', isCore: true },
            90: { value: '#e2e1ec', isCore: true },
            92: { value: '#e8e7f2', isCore: true },
            94: { value: '#eeedf8', isCore: true },
            95: { value: '#f1f0fb', isCore: true },
            96: { value: '#f4f2fe', isCore: true },
            98: { value: '#fbf8ff', isCore: true },
            99: { value: '#fefbff', isCore: true },
            100: { value: '{colors.white}', isCore: true },
        },
        error: {
            0: { value: '{colors.black}', isCore: true },
            10: { value: '#410002', isCore: true },
            20: { value: '#690005', isCore: true },
            30: { value: '#93000a', isCore: true },
            40: { value: '#b81f1e', isCore: true },
            50: { value: '#db3a33', isCore: true },
            60: { value: '#ff5449', isCore: true },
            70: { value: '#ff897d', isCore: true },
            80: { value: '#ffb4ab', isCore: true },
            87: { value: '#ffcfc9', isCore: true },
            90: { value: '#ffdad6', isCore: true },
            92: { value: '#ffe2de', isCore: true },
            94: { value: '#ffe9e6', isCore: true },
            95: { value: '#ffedea', isCore: true },
            96: { value: '#fff0ee', isCore: true },
            98: { value: '#fff8f7', isCore: true },
            99: { value: '#fffbff', isCore: true },
            100: { value: '{colors.white}', isCore: true },
        },
    },
}
