# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          # persist-credentials: global

      - uses: actions/setup-node@v2
        with:
          node-version: "14.18.2"
      - run: git config --global credential.helper store
      - run: npm install # TODO: find out why "npm ci" doesn't install lodash dependency
      - run: npm run test
      # - run: npm run prettier
      # - name: Commit changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: ran prettier
      #     branch: master
