
name: Code Inspector

on:
  schedule: 
    - cron: '49 21 * * *' # will run arount 3:19AM IST, 21:49PM is in UTC here
  
  workflow_dispatch:

jobs:
  code-inspector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16.0.0"
      - run: git config --global credential.helper store
      - run: npm install
      - run: npm run lint

  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16.0.0"
      - run: git config --global credential.helper store
      - run: npm install
      - run: npm run check-types
